name: health_social_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  scoped_model: ^1.0.1
  flutter_rating: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/background.jpg
    - assets/images/background2.jpg
    - assets/images/runner1.jpg
    - assets/images/runner2.jpg
    - assets/images/cake.jpg
    - assets/images/profile.png
    - assets/images/profileDiCaprio.jpg
    - assets/images/blueRedOmbre.jpg
    - assets/images/pinkOmbre.png
    - assets/images/football.jpg
    - assets/images/healthBowl.jpg
    - assets/images/profile_pic.jpg
    - assets/images/profile_pic2.jpg
    - assets/images/bowl1.jpg
    - assets/images/bowl2.jpg
    - assets/images/protein1.jpg
    - assets/images/protein2.jpg
    - assets/images/protein3.jpg
    - assets/images/burger1.jpg
    - assets/images/burger2.jpg
    - assets/images/sushi.jpg
    - assets/images/placeholderImage.jpg
    - assets/images/default.png
    - assets/images/logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/comfortaa/Comfortaa-Light.ttf

    - family: myriad-pro-light
      fonts: 
        - asset: assets/fonts/myriad-pro/myriadpro-light.otf

    - family: myriad-pro-bold
      fonts:
        - asset: assets/fonts/myriad-pro/MyriadPro-Bold.otf
        # - asset: assets/fonts/comfortaa/Comfortaa-Bold.ttf
        #   style: bold
        # - asset: assets/fonts/comfortaa/Comfortaa-Regular.ttf
        #   style: regular
        #  style: light
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
